version: "3.7"
name: webgis
services:
  # ReactJS Frontend
  reactjs:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    container_name: reactjs
    restart: always
    working_dir: /usr/src/app
    command: npm start  # Usa nodemon y webpack --watch | # npm start para producción
    ports:
      - "${NODE_PORT}:4000"
    volumes:
      - './outputs_shared:/usr/src/app/outputs_shared'
    networks:
      - frontend
      - backend
  express:
    build:
      context: .
      dockerfile: docker/express/Dockerfile  # Usamos la misma imagen que React
    container_name: express
    restart: always
    working_dir: /usr/src/app
    command: npm start
    ports:
      - "${NODE_SERVER_PORT}:4001"
    volumes:
      - './outputs_shared:/usr/src/app/outputs_shared'
    networks:
      - frontend
      - backend
  earthengine:
    build:
      context: ./docker/earthengine-server-nodejs
      dockerfile: docker/ee.Dockerfile
    image: roadeye-earthengine:latest
    restart: always
    ports:
      - "${EARTHENGINE_PORT}:3000"
    networks:
      - backend
    mem_limit: 1g
  postgres:
    image: kartoza/postgis:14-3.3
    container_name: postgres
    hostname: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASS: '${DB_PASSWORD}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_MULTIPLE_EXTENSIONS: postgis,hstore,postgis_topology,postgis_raster,pgrouting
    volumes:
      - ./docker/postgresql/data:/var/lib/postgresql
      - ./docker/postgresql/backups:/var/backups
    networks:
      - backend
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: tidop@tidop.es
      PGADMIN_DEFAULT_PASSWORD: crj#roadeye#21
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - backend
  geoserver:
    image: kartoza/geoserver:2.22.2
    restart: always
    ports:
      - "${GEOSERVER_PORT}:8080"
    volumes:
      - ./docker/geoserver:/opt/geoserver/data_dir
      - ./docker/geoserver/data:/opt/geoserver/data_dir/data
    environment:
      GEOSERVER_DATA_DIR: /opt/geoserver/data_dir
      GEOSERVER_ADMIN_USER: admin
      GEOSERVER_ADMIN_PASSWORD: crj#roadeye#21
      STABLE_EXTENSIONS: sldservice-plugin,feature-pregeneralized-plugin,css-plugin,importer-plugin
      COMMUNITY_EXTENSIONS: cog-plugin
      INITIAL_MEMORY: 2G
      MAXIMUM_MEMORY: 4G
    networks:
      - backend
    mem_limit: 2g
  vhr:
    build:
      context: ./docker/vhr_fastapi
      dockerfile: Dockerfile
    volumes:
      - ./outputs_shared:/tmp
    ports:
      - "8000:8000"
    networks:
      - frontend
      - backend
networks:
  frontend:
  backend:
volumes:
  postgres-data:
  pgadmin-data:
#     redis-data:
#     geoserver-data:
