version: "3.7"
name: webgis
services:
  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    container_name: node
    restart: always
    working_dir: /usr/src/app
    command: npm start  # Usa nodemon y webpack --watch | # npm start para producción
    ports:
      - "${NODE_PORT}:4000"
    volumes:
      - '.:/usr/src/app'
    networks:
      - frontend
      - backend
  earthengine:
    build:
      context: ./docker/earthengine-server-nodejs
      dockerfile: docker/ee.Dockerfile
    image: roadeye-earthengine:latest
    restart: always
    ports:
      - "${EARTHENGINE_PORT}:3000"
    networks:
      - backend
    mem_limit: 1g
  postgres:
    image: kartoza/postgis:14-3.3
    container_name: postgres
    hostname: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASS: '${DB_PASSWORD}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_MULTIPLE_EXTENSIONS: postgis,hstore,postgis_topology,postgis_raster,pgrouting
    volumes:
      - ./docker/postgresql/data:/var/lib/postgresql
      - ./docker/postgresql/backups:/var/backups
    networks:
      - backend
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: tidop@tidop.es
      PGADMIN_DEFAULT_PASSWORD: crj#enagas#21
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - backend
networks:
  frontend:
  backend:
volumes:
  postgres-data:
  pgadmin-data:
#     redis-data:
#     geoserver-data:
