name: gee_catalog
on: 
  workflow_dispatch:
  schedule:
    - cron: '15 0 1 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -U setuptools
          pip install pendulum beautifulsoup4 requests natsort pandas

      - name: Script check 1
        run: python ./.github/download_catalog.py
      
      - name: Script check 2
        run: python ./.github/parse_catalog.py

      - name: file_check
        run: ls -l -a

      - name: commit files
        continue-on-error: true
        run: |
          today=$(date +"%Y-%m-%d")
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "updated datasets ${today} UTC" -a
          git pull origin main

      - name: push changes
        continue-on-error: true
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
