FROM node:20.5.1

# Establecer el directorio de trabajo
WORKDIR /usr/src/app

# Copiar archivos de dependencias
COPY package*.json ./

# Instalar todas las dependencias del proyecto localmente en node_modules dentro del contenedor
RUN npm install
RUN npm i -D @craco/craco
RUN npm i web-vitals

# Copiar todo el código fuente
COPY . .

# Exponer el puerto de la aplicación
EXPOSE 3000

# Comando por defecto al iniciar el contenedor
CMD ["npm", "start"]